### ISSUE TITLE
dumb question - calculating price?

### ISSUE THREAD

**Issue by mewmix** [0xfffangel/multidex-python#2]
extending the example code - 

```
from multidex import Uniswap

uniswap = Uniswap()
USDC = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"

print("reserves: ", uniswap.reserves(USDC))
print("liquidity: ", uniswap.liquidity(USDC))
print("reserve_ratio: ", uniswap.reserve_ratio(USDC))
print("price: ", uniswap.price(USDC))


output=f"{uniswap.price(USDC):.18f}"

print(output) 

```

would this suffice for most examples in converting the float to a legible number? Forgive my dumb question! Just poking around! Excellent work either way, would it be okay if I made a PR for the Telos evm dex?

**Comment by 0xfffangel** [comment]
Hi @mewmix, nice touch! free to open PR :-)

**Comment by 0xfffangel** [comment]
Update demo example in documentation with price formatting
