### ISSUE TITLE
ContractLogicError: execution reverted

### ISSUE THREAD

**Issue by bL34ch-exe** [0xfffangel/multidex-python#4]
When just applying that i get this error : 
from multidex import Uniswap

uniswap = Uniswap()
USDC = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"

print("reserves: ", uniswap.reserves(USDC))
print("liquidity: ", uniswap.liquidity(USDC))
print("reserve_ratio: ", uniswap.reserve_ratio(USDC))
print("price: ", uniswap.price(USDC))

**Comment by 0xfffangel** [comment]
thank to remind me to update the demo example in the doc.
could you test with the following?


```python
from web3dex.ethereum import Uniswap

uniswap = Uniswap()
USDC = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"

print("reserves: ", uniswap.reserves(USDC))
print("liquidity_in: ", uniswap.liquidity_in(USDC))
print("liquidity_out: ", uniswap.liquidity_out(USDC))
print("reserve_ratio: ", uniswap.reserve_ratio(USDC))
print("price: ", uniswap.price(USDC))
```

**Comment by bL34ch-exe** [comment]
yeah it works perfectly !
